### ISSUE TITLE
Error preventing game start

### ISSUE THREAD

**Issue by Ixolaro** [boiscljo/SBA#74] opened 2024-07-22 17:12 UTC
[17:06:59 ERROR]: An exception occurred serializing packet of class: ClientboundPlayerInfoPacket
[17:06:59 WARN]: java.lang.UnsupportedOperationException: Can't unwrap object to java.lang.Integer

[17:06:59 WARN]:        at sba.sl.u.BasicNullableWrapper.as(BasicNullableWrapper.java:57)

[17:06:59 WARN]:        at sba.sl.impl.bukkit.BukkitServer.getProtocolVersion0(BukkitServer.java:606)

[17:06:59 WARN]:        at sba.sl.Server.getProtocolVersion(Server.java:124)

[17:06:59 WARN]:        at sba.sl.p.PacketWriter.protocol(PacketWriter.java:591)

[17:06:59 WARN]:        at sba.sl.p.ClientboundPlayerInfoPacket.write(ClientboundPlayerInfoPacket.java:43)

[17:06:59 WARN]:        at sba.sl.impl.bukkit.packet.BukkitPacketMapper.sendPacket0(BukkitPacketMapper.java:58)

[17:06:59 WARN]:        at sba.sl.p.PacketMapper.sendPacket(PacketMapper.java:62)

[17:06:59 WARN]:        at sba.sl.p.AbstractPacket.sendPacket(AbstractPacket.java:45)

[17:06:59 WARN]:        at sba.sl.npc.NPCImpl.lambda$scheduleTabHide$3(NPCImpl.java:288)

[17:06:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)

[17:06:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)

[17:06:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)

[17:06:59 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)

[17:06:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)

[17:06:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)

[17:06:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Ixolaro** [comment] 2024-07-22 17:13
Latest Java
Ubunntu server

**Comment by Ixolaro** [comment] 2024-07-22 17:13
PaperMC 1.8.8
Vulcan Anticheat

**Comment by Misat11** [comment] 2024-07-22 17:38
duplicate of #70, update to 1.5.13.2

**Closed as not planned** 2024-07-22 20:11 UTC
